fix: update github actions

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -50,44 +50,44 @@ jobs:
                 NODE_OPTIONS: --max-old-space-size=4000
                 NODE_ENV: production
               run: npm run build
-            - name: Store Build Output
-              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
-              with:
-                name: build-output
-                path: ./build
-            - name: Store Dist Output
-              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
-              with:
-                name: dist-output
-                path: ./dist
-            - run: |
-                for F in chrome chromium chromedriver; do
-                    which $F && $F --version || echo Not found: $F
-                done
-            - name: Run Integration Tests
-              env:
-                  JEST_JUNIT_OUTPUT_NAME: results.txt
-                  JEST_JUNIT_OUTPUT_DIR: test-results/integration
-              run: npm run test:integration -- --reporters="default" --reporters="jest-junit"
-            - name: Store Test Results
-              if: always() # Even if tests fail
-              uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
-              with:
-                name: test-output
-                path: ./test-results/* # Both unit and integration test results
-            - run: |
-                if [[ ${{contains(github.ref, 'hotfix')}}  ]]; then
-                sed -e "s|hotfix/REPLACE|${{ github.ref_name }}|" --in-place release.config.js
-                fi
-            - name: Semantic Release
-              env:
-                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              run: npx --no -- semantic-release
-            - name: Deploy playground to GitHub Pages
-              uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
-              if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
-              with:
-                github_token: ${{ secrets.GITHUB_TOKEN }}
-                publish_dir: ./build
-                full_commit_message: "Build for ${{ github.sha }} ${{ github.event.head_commit.message }}"
+            # - name: Store Build Output
+            #   uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
+            #   with:
+            #     name: build-output
+            #     path: ./build
+            # - name: Store Dist Output
+            #   uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
+            #   with:
+            #     name: dist-output
+            #     path: ./dist
+            # - run: |
+            #     for F in chrome chromium chromedriver; do
+            #         which $F && $F --version || echo Not found: $F
+            #     done
+            # - name: Run Integration Tests
+            #   env:
+            #       JEST_JUNIT_OUTPUT_NAME: results.txt
+            #       JEST_JUNIT_OUTPUT_DIR: test-results/integration
+            #   run: npm run test:integration -- --reporters="default" --reporters="jest-junit"
+            # - name: Store Test Results
+            #   if: always() # Even if tests fail
+            #   uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
+            #   with:
+            #     name: test-output
+            #     path: ./test-results/* # Both unit and integration test results
+            # - run: |
+            #     if [[ ${{contains(github.ref, 'hotfix')}}  ]]; then
+            #     sed -e "s|hotfix/REPLACE|${{ github.ref_name }}|" --in-place release.config.js
+            #     fi
+            # - name: Semantic Release
+            #   env:
+            #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            #   run: npx --no -- semantic-release
+            # - name: Deploy playground to GitHub Pages
+            #   uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
+            #   if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
+            #   with:
+            #     github_token: ${{ secrets.GITHUB_TOKEN }}
+            #     publish_dir: ./build
+            #     full_commit_message: "Build for ${{ github.sha }} ${{ github.event.head_commit.message }}"
